### ISSUE TITLE
Source code of the Android App ?

### ISSUE THREAD

**Issue by nwabeen** [IMSHOX/OXOTP#1]
Hello,
First, thank you for your awesome work ! This is a great idea, the M5stickC is the perfect low-cost device for this use.

I wanted to know if you planned to release the source code of the Android app ? This would be useful if someone was willing to fork or continue the development in the future.

Have a good day and keep up your good work 😁 !

**Comment by IMSHOX** [comment]
Hi nwabeen
thanks for your support 😁!!!!!!

yes, I will release the source code after put it in AppStore, thanks a lot for your support that makes me feel good.

Apple didn't make work easy to develop in windows, so I had to buy a mac for that.




// message for Apple:  please give the developers the freedom to choose the hardware for app development.
