### ISSUE TITLE
Screen is vertical instead of horizontal

### ISSUE THREAD

**Issue by saqeria** [IMSHOX/OXOTP#2]
Hi, the screen is currently working vertically and is not readable because the text is outside of the screen ratio. How do you fix this?

**Comment by IMSHOX** [comment]
Hi, saqeria.

 I will make an update now, thanks for the feedback.

**Comment by saqeria** [comment]
> 
> 
> Hi, saqeria.
> 
> I will make an update now, thanks for the feedback.

Fyi I'm using trying to install it on the m5stickc plus. After I flashed the file the oxotp applications is outside the screen ratio of the device. I tried different settings within the esp32 flasher but unfortunately without success.. If you happen to upload the updated version now I'll be able to check if the bug is fixed. Btw I love the project you invented it's really secure and usefull, would love to check it out if it is finally working 👍

**Comment by IMSHOX** [comment]
can you send me a picture for M5StickC plus in my contact@imshox.ml. 

I never developed it for M5StickC plus, I will make a change, give me more information with pictures.

**Comment by saqeria** [comment]
> 
> 
> can you send me a picture for M5StickC plus in my [contact@imshox.ml](mailto:contact@imshox.ml).
> 
> I never developed it for M5StickC plus, I will make a change, give me more information with pictures.

Thank you I've send you a mail with more information, output log and picture of the m5stick plus's screen.
